from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


path = Path("crates/dartscope-index/src/incremental.rs")
text = path.read_text()
text = replace_once(text, "    DartIdentifierReference, DartIdentifierReferenceResolution,\n", "    DartIdentifierReference, DartIdentifierReferenceResolution, DartLexicalBinding,\n", "import")
text = replace_once(text, "    identifier_reference_resolutions: Arc<DartIdentifierReferenceResolutionAnalysis>,\n}", "    identifier_reference_resolutions: Arc<DartIdentifierReferenceResolutionAnalysis>,\n    identifier_references: Arc<Vec<DartIdentifierReference>>,\n    lexical_bindings: Arc<Vec<DartLexicalBinding>>,\n    options: DartIndexOptions,\n}", "snapshot fields")
text = replace_once(text, "    pub fn identifier_reference_resolutions(&self) -> &DartIdentifierReferenceResolutionAnalysis {\n        &self.identifier_reference_resolutions\n    }\n}", "    pub fn identifier_reference_resolutions(&self) -> &DartIdentifierReferenceResolutionAnalysis {\n        &self.identifier_reference_resolutions\n    }\n\n    pub fn identifier_references(&self) -> &[DartIdentifierReference] {\n        self.identifier_references.as_slice()\n    }\n\n    pub fn lexical_bindings(&self) -> &[DartLexicalBinding] {\n        self.lexical_bindings.as_slice()\n    }\n\n    pub fn options(&self) -> &DartIndexOptions {\n        &self.options\n    }\n\n    pub fn project_reference_analysis(&self) -> DartProjectReferenceAnalysis {\n        DartProjectReferenceAnalysis {\n            project: self.project.as_ref().clone(),\n            references: self.identifier_references.as_ref().clone(),\n            bindings: self.lexical_bindings.as_ref().clone(),\n        }\n    }\n}", "snapshot accessors")
text = replace_once(text, "    references_by_path: BTreeMap<String, Vec<DartIdentifierReference>>,\n", "    references_by_path: BTreeMap<String, Vec<DartIdentifierReference>>,\n    bindings_by_path: BTreeMap<String, Vec<DartLexicalBinding>>,\n", "index field")
text = replace_once(text, "        Self::from_inputs(project, BTreeMap::new(), options)\n", "        Self::from_inputs(project, BTreeMap::new(), BTreeMap::new(), options)\n", "project ctor")
text = replace_once(text, "        let references_by_path = group_references(analysis.references);\n        Self::from_inputs(analysis.project, references_by_path, options)\n", "        let references_by_path = group_references(analysis.references);\n        let bindings_by_path = group_bindings(analysis.bindings);\n        Self::from_inputs(analysis.project, references_by_path, bindings_by_path, options)\n", "reference ctor")
text = replace_once(text, "        references_by_path: BTreeMap<String, Vec<DartIdentifierReference>>,\n        options: DartIndexOptions,\n", "        references_by_path: BTreeMap<String, Vec<DartIdentifierReference>>,\n        bindings_by_path: BTreeMap<String, Vec<DartLexicalBinding>>,\n        options: DartIndexOptions,\n", "from inputs")
text = replace_once(text, "        let identifier_reference_resolutions = Arc::new(identifier_reference_resolutions);\n", "        let identifier_reference_resolutions = Arc::new(identifier_reference_resolutions);\n        let identifier_references = Arc::new(aggregate_references(&references_by_path));\n        let lexical_bindings = Arc::new(aggregate_bindings(&bindings_by_path));\n", "initial facts")
text = replace_once(text, "            identifier_reference_resolutions,\n        });\n", "            identifier_reference_resolutions,\n            identifier_references,\n            lexical_bindings,\n            options: options.clone(),\n        });\n", "initial snapshot")
text = replace_once(text, "            references_by_path,\n            uri_references_by_path,\n", "            references_by_path,\n            bindings_by_path,\n            uri_references_by_path,\n", "index init")
text = replace_once(text, "        self.upsert_file_internal(file, None)\n", "        self.upsert_file_internal(file, None, None)\n", "plain upsert")
text = replace_once(text, "        self.upsert_file_internal(analysis.file, Some(analysis.references))\n", "        self.upsert_file_internal(\n            analysis.file,\n            Some(analysis.references),\n            Some(analysis.bindings),\n        )\n", "reference upsert")
text = replace_once(text, "        references: Option<Vec<DartIdentifierReference>>,\n    ) -> DartWorkspaceUpdate {\n", "        references: Option<Vec<DartIdentifierReference>>,\n        bindings: Option<Vec<DartLexicalBinding>>,\n    ) -> DartWorkspaceUpdate {\n", "upsert signature")
text = replace_once(text, "        let old_file = self.files.get(&path).cloned();\n", "        let new_bindings = bindings\n            .map(|bindings| normalize_bindings_for_path(&path, bindings))\n            .unwrap_or_default();\n        let old_file = self.files.get(&path).cloned();\n", "new bindings")
text = replace_once(text, "        let references_changed = old_references != new_references;\n\n        if old_file.as_ref() == Some(&file) && !references_changed {\n", "        let old_bindings = self\n            .bindings_by_path\n            .get(&path)\n            .cloned()\n            .unwrap_or_default();\n        let references_changed = old_references != new_references;\n        let bindings_changed = old_bindings != new_bindings;\n\n        if old_file.as_ref() == Some(&file) && !references_changed && !bindings_changed {\n", "change detection")
text = replace_once(text, "            Some(old) => file_rebuild_plan(old, &file, references_changed),\n", "            Some(old) => file_rebuild_plan(old, &file, references_changed || bindings_changed),\n", "rebuild plan")
text = replace_once(text, "        if new_references.is_empty() {\n            self.references_by_path.remove(&path);\n        } else {\n            self.references_by_path.insert(path.clone(), new_references);\n        }\n        self.rebuild(\n", "        if new_references.is_empty() {\n            self.references_by_path.remove(&path);\n        } else {\n            self.references_by_path.insert(path.clone(), new_references);\n        }\n        if new_bindings.is_empty() {\n            self.bindings_by_path.remove(&path);\n        } else {\n            self.bindings_by_path.insert(path.clone(), new_bindings);\n        }\n        self.rebuild(\n", "store bindings")
text = replace_once(text, "        self.references_by_path.remove(&path);\n        self.rebuild(\n", "        self.references_by_path.remove(&path);\n        self.bindings_by_path.remove(&path);\n        self.rebuild(\n", "remove bindings")
text = replace_once(text, "        self.counters.generations += 1;\n        let generation = old.generation + 1;\n", "        let identifier_references = Arc::new(aggregate_references(&self.references_by_path));\n        let lexical_bindings = Arc::new(aggregate_bindings(&self.bindings_by_path));\n\n        self.counters.generations += 1;\n        let generation = old.generation + 1;\n", "rebuilt facts")
text = replace_once(text, "            identifier_reference_resolutions,\n        });\n\n        DartWorkspaceUpdate {\n", "            identifier_reference_resolutions,\n            identifier_references,\n            lexical_bindings,\n            options: self.options.clone(),\n        });\n\n        DartWorkspaceUpdate {\n", "rebuilt snapshot")
text = replace_once(text, "fn group_references(\n", "fn aggregate_references(\n    references_by_path: &BTreeMap<String, Vec<DartIdentifierReference>>,\n) -> Vec<DartIdentifierReference> {\n    references_by_path\n        .values()\n        .flat_map(|references| references.iter().cloned())\n        .collect()\n}\n\nfn aggregate_bindings(\n    bindings_by_path: &BTreeMap<String, Vec<DartLexicalBinding>>,\n) -> Vec<DartLexicalBinding> {\n    bindings_by_path\n        .values()\n        .flat_map(|bindings| bindings.iter().cloned())\n        .collect()\n}\n\nfn group_bindings(\n    bindings: Vec<DartLexicalBinding>,\n) -> BTreeMap<String, Vec<DartLexicalBinding>> {\n    let mut grouped: BTreeMap<String, Vec<DartLexicalBinding>> = BTreeMap::new();\n    for mut binding in bindings {\n        binding.source_path = normalize_path(binding.source_path);\n        grouped.entry(binding.source_path.clone()).or_default().push(binding);\n    }\n    for bindings in grouped.values_mut() {\n        sort_and_deduplicate_bindings(bindings);\n    }\n    grouped\n}\n\nfn group_references(\n", "aggregate bindings")
text = replace_once(text, "fn sort_and_deduplicate_references(references: &mut Vec<DartIdentifierReference>) {\n", "fn normalize_bindings_for_path(\n    path: &str,\n    bindings: Vec<DartLexicalBinding>,\n) -> Vec<DartLexicalBinding> {\n    let mut bindings: Vec<_> = bindings\n        .into_iter()\n        .map(|mut binding| {\n            binding.source_path = path.to_string();\n            binding\n        })\n        .collect();\n    sort_and_deduplicate_bindings(&mut bindings);\n    bindings\n}\n\nfn sort_and_deduplicate_bindings(bindings: &mut Vec<DartLexicalBinding>) {\n    bindings.sort_by(|left, right| {\n        (\n            &left.source_path,\n            left.declaration_span.byte_start,\n            left.declaration_span.byte_end,\n            left.kind,\n            &left.name,\n            &left.symbol_id,\n        )\n            .cmp(&(\n                &right.source_path,\n                right.declaration_span.byte_start,\n                right.declaration_span.byte_end,\n                right.kind,\n                &right.name,\n                &right.symbol_id,\n            ))\n    });\n    bindings.dedup_by(|left, right| {\n        left.source_path == right.source_path\n            && left.symbol_id == right.symbol_id\n            && left.declaration_span.byte_start == right.declaration_span.byte_start\n            && left.declaration_span.byte_end == right.declaration_span.byte_end\n    });\n}\n\nfn sort_and_deduplicate_references(references: &mut Vec<DartIdentifierReference>) {\n", "binding normalization")
path.write_text(text)

path = Path("crates/dartscope-index/src/navigation.rs")
text = path.read_text()
text = replace_once(text, "use crate::lexical_bindings::resolve_lexical_binding;\n", "use crate::incremental::DartWorkspaceSnapshot;\nuse crate::lexical_bindings::resolve_lexical_binding;\n", "snapshot import")
text = replace_once(text, "    pub fn with_options(\n        analysis: &DartProjectReferenceAnalysis,\n        options: &DartIndexOptions,\n    ) -> Self {\n        let uri_graph = Arc::new(build_uri_graph_with_options(&analysis.project, options));\n        let part_links = analyze_part_links_with_graph(&analysis.project, &uri_graph);\n        let namespace = NamespaceResolver::from_analyses(\n            &analysis.project,\n            options,\n            Arc::clone(&uri_graph),\n            &part_links,\n        );\n", "    pub fn with_options(\n        analysis: &DartProjectReferenceAnalysis,\n        options: &DartIndexOptions,\n    ) -> Self {\n        let uri_graph = Arc::new(build_uri_graph_with_options(&analysis.project, options));\n        let part_links = analyze_part_links_with_graph(&analysis.project, &uri_graph);\n        Self::from_components(analysis, options, uri_graph, &part_links)\n    }\n\n    pub fn from_snapshot(snapshot: &DartWorkspaceSnapshot) -> Self {\n        let analysis = snapshot.project_reference_analysis();\n        Self::from_components(\n            &analysis,\n            snapshot.options(),\n            Arc::new(snapshot.uri_graph().clone()),\n            snapshot.part_links(),\n        )\n    }\n\n    fn from_components(\n        analysis: &DartProjectReferenceAnalysis,\n        options: &DartIndexOptions,\n        uri_graph: Arc<DartUriGraph>,\n        part_links: &dartscope_core::DartPartLinkAnalysis,\n    ) -> Self {\n        let namespace = NamespaceResolver::from_analyses(\n            &analysis.project,\n            options,\n            Arc::clone(&uri_graph),\n            part_links,\n        );\n", "snapshot constructor")
path.write_text(text)
